name: CI
on:
  pull_request:
    branches:
      - master

jobs:
  format_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Cache node_modules
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'yarn'
      - run: yarn install --frozen-lockfile --non-interactive
      - run: npx nx run-many --target=test --all --parallel --max-parallel=3
