name: CI
on:
  push:
    branches:
      # Change this if your primary branch is not main
      - master
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      # Cache node_modules
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'yarn'
      - run: yarn install --frozen-lockfile --non-interactive
      - run: npx nx format:check
      - run: npx nx run-many --target=test --all --parallel --max-parallel=3
